# Generated by Django 5.0.6 on 2024-09-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_korder_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='korder',
            name='payment_mode',
            field=models.CharField(choices=[('COD', 'Cod'), ('CARD', 'Card')], default='COD', max_length=50),
        ),
        migrations.AddField(
            model_name='korder',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='Processing', max_length=50),
        ),
    ]
