# Generated by Django 5.0.6 on 2024-09-24 10:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_korder_payment_mode_korder_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KOrder',
            new_name='Order',
        ),
    ]
